# Generated by Django 5.1.5 on 2025-01-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Заголовок новости')),
                ('description', models.CharField(max_length=200, verbose_name='Описание новости')),
                ('text', models.TextField(verbose_name='Текст новости')),
                ('status', models.CharField(choices=[('draft', 'На модерации'), ('publish', 'Готово к публикации'), ('inactive', 'Неактивная')], default='draft', max_length=8)),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
